# データ増強ジョブ全体の設定
augmentation:
  dataset:
    # 増強に利用する元データの場所と列情報
    input_path: "data/marc_ja_train_subset.jsonl"
    text_column: "sentence"      # レビュー本文が格納されている列名
    label_column: "label"        # 感情ラベルが格納されている列名
    label_names:
      - positive                  # ラベルID 0 の名称
      - negative                  # ラベルID 1 の名称
    default_output_prefix: "data/marc_ja_augmented"  # 生成データの保存プレフィックス

  model:
    # モデルの読み込み方法。"unsloth" か "huggingface" を選択
    provider: "huggingface"
    name: "google/gemma-3-4b-it"  # 既定で利用するモデル
    device_map: 0              # モデルを配置するデバイス指定（0 は単一GPU）
    max_seq_length: 4096        # 推論時の最大トークン長
    # Hugging Face Transformers を使う場合はフル精度（FP16/FP32）を既定とし、
    # 4bit 量子化を試す場合は下記のコメントアウトを解除して利用してください。
    # 量子化指定例（GPU が対応していないと NaN が発生するため注意）:
    quantization: "4bit"
    bnb_4bit_use_double_quant: true  
    bnb_4bit_quant_type: "nf4"
    quantization_compute_dtype: bfloat16
    torch_dtype: bfloat16

    tokenizer:
      use_fast: true

  generation_defaults:
    # 推論パラメータのデフォルト値。プロンプト単位で上書き可能
    max_new_tokens: 256
    temperature: 1.0
    top_p: 0.95
    top_k: 64
    repetition_penalty: 1.0
    do_sample: true
    num_generations_per_sample: 1
    batch_size: 6
    seed: 42

  prompts:
    # 生成タスクごとのプロンプト定義
    zero_shot:
      description: "元レビューに依存せず、新規レビューを生成"
      generation_multiplier: 5.0
      output_path_template: "data/marc_ja_augmented_zero_shot_run{run_index}.jsonl"
      system_prompt: ""
      user_prompt_template: |-
        あなたは日本語レビューを作成するアシスタントです。以下の条件を守り、指定された感情ラベルに合う自然なレビュー文を1件出力してください。

        感情ラベル:
        {label_name}

        制約:
        - 感情ラベルに一致するトーンと内容にすること
        - レビュー以外の説明や考察、ラベルの再掲はしないこと

        出力:

    few_shot:
      description: "既存レビューをヒントに、新規レビューを生成"
      generation_multiplier: 5.0
      output_path_template: "data/marc_ja_augmented_few_shot_run{run_index}.jsonl"
      system_prompt: ""
      user_prompt_template: |-
        あなたは日本語レビューを改善するアシスタントです。参考として与えられたレビューと同じ感情ラベルを維持しつつ、内容が被らない新しいレビューを1件生成してください。レビュー以外の説明文は不要です。

        参考レビュー:
        {input_text}

        感情ラベル:
        {label_name}

        出力:

    ja_to_en_translation:
      description: "日本語レビューを英語に翻訳"
      generation_multiplier: 5.0
      generation:
        num_generations_per_sample: 1
      output_path_template: "data/marc_ja_augmented_ja_to_en_run{run_index}.jsonl"
      system_prompt: ""
      user_prompt_template: |-
        You are a professional Japanese-to-English translator. Translate the following Japanese review into natural English that reflects the requested sentiment label. Output only the translated review text.

        Japanese review:
        {input_text}

        Sentiment label:
        {label_name}

        Response:

    en_to_ja_translation:
      description: "英語レビューを日本語に翻訳"
      dataset:
        input_paths:
          - "data/marc_ja_augmented_ja_to_en_run1.jsonl"
          - "data/marc_ja_augmented_ja_to_en_run2.jsonl"
          - "data/marc_ja_augmented_ja_to_en_run3.jsonl"
          - "data/marc_ja_augmented_ja_to_en_run4.jsonl"
          - "data/marc_ja_augmented_ja_to_en_run5.jsonl"
      generation_multiplier: 1.0
      generation:
        num_generations_per_sample: 1
      output_path_template: "data/{dataset_name}_en_to_ja.jsonl"
      system_prompt: ""
      user_prompt_template: |-
        あなたは英語レビューを日本語へ翻訳するアシスタントです。与えられた感情ラベルを保ちながら、自然な日本語レビューを1件出力してください。レビュー以外の説明は不要です。

        英語レビュー:
        {input_text}

        感情ラベル:
        {label_name}

        出力:
